import Link from 'next/link';
import { getReservationRequests, RESERVATION_PAGE_SIZE } from '@/lib/reservationRequests.mjs';
import { formatDateOnly, SLOT_LABELS, parseSlot } from '@/lib/reservationRequestsView.mjs';
import { parsePage, parseYear } from '@/lib/mazeEntriesView.mjs';
export const dynamic='force-dynamic';
export const metadata={title:'Reservation Requests | OMPP Admin'};
const dt=new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'America/New_York'});
const date=new Intl.DateTimeFormat('en-US',{dateStyle:'full',timeZone:'UTC'});
function url(page,year,slot){const p=new URLSearchParams();if(year)p.set('year',year);if(slot)p.set('slot',slot);if(page>1)p.set('page',page);return `/reservation-requests${p.size?`?${p}`:''}`;}
export default async function Page({searchParams}){const p=await searchParams;const year=parseYear(p?.year);const slot=parseSlot(p?.slot);const data=await getReservationRequests({page:parsePage(p?.page),year,slot});const ep=new URLSearchParams();if(year)ep.set('year',year);if(slot)ep.set('slot',slot);return <main className="px-4 py-8 sm:px-8">
  <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-widest text-foreground/60">Form submissions</p><h1 className="text-3xl font-bold">Reservation requests</h1><p className="mt-2 text-foreground/70">Requests are not confirmed bookings.</p></div><a className="h-fit rounded-lg bg-accent px-4 py-2 font-semibold text-white" href={`/reservation-requests/export${ep.size?`?${ep}`:''}`}>Download CSV</a></div>
  <form className="mb-6 flex flex-wrap items-end gap-3"><label className="font-semibold">Year<select className="block rounded border p-2" defaultValue={year??''} name="year"><option value="">All</option>{data.years.map(y=><option key={y}>{y}</option>)}</select></label><label className="font-semibold">Time<select className="block rounded border p-2" defaultValue={slot??''} name="slot"><option value="">All</option>{Object.entries(SLOT_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className="rounded border px-4 py-2 font-semibold">Apply</button><Link className="p-2 underline" href="/reservation-requests">Clear</Link></form>
  <p className="mb-3 text-sm">Showing {data.totalEntries?((data.currentPage-1)*RESERVATION_PAGE_SIZE)+1:0}–{Math.min(data.currentPage*RESERVATION_PAGE_SIZE,data.totalEntries)} of {data.totalEntries}</p>
  <div className="space-y-4">{data.entries.map(e=><article className="rounded-xl border border-foreground/20 p-5 shadow-sm" key={e.id}><div className="flex flex-wrap justify-between gap-2"><div><h2 className="text-xl font-bold">#{e.id} · {e.name}</h2><p><a className="underline" href={`mailto:${e.email}`}>{e.email}</a> · <a className="underline" href={`tel:${e.phone_normalized}`}>{e.phone}</a></p></div><p className="text-sm text-foreground/60">Submitted {dt.format(new Date(e.created_at))}</p></div><dl className="mt-4 grid gap-3 sm:grid-cols-3"><div><dt className="font-semibold">Preferred date</dt><dd>{date.format(new Date(`${formatDateOnly(e.preferred_date)}T00:00:00Z`))}</dd></div><div><dt className="font-semibold">Preferred time</dt><dd>{SLOT_LABELS[e.preferred_time_slot]}</dd></div><div><dt className="font-semibold">Price acknowledged</dt><dd>${(e.price_cents_snapshot/100).toFixed(2)}</dd></div></dl>{e.fallback_dates&&<p className="mt-3"><strong>Fallbacks:</strong> {e.fallback_dates}</p>}{e.additional_comments&&<p className="mt-2"><strong>Comments:</strong> {e.additional_comments}</p>}</article>)}{!data.entries.length&&<p className="rounded-xl border border-dashed p-8 text-center">No requests match this filter.</p>}</div>
  {data.totalPages>1&&<nav className="mt-6 flex justify-between">{data.currentPage>1?<Link href={url(data.currentPage-1,year,slot)}>Previous</Link>:<span/>}<span>Page {data.currentPage} of {data.totalPages}</span>{data.currentPage<data.totalPages?<Link href={url(data.currentPage+1,year,slot)}>Next</Link>:<span/>}</nav>}
  </main>}
